import { createContext, useContext, useEffect, useState } from "react";
import { fetchSiteSettings, type PayloadSiteSettings } from "@/lib/payload";

export type Language = "en" | "ar";

interface LanguageContextValue {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  dir: "ltr" | "rtl";
  isArabic: boolean;
}

const translations = {
  en: {
    // NAV
    home: "Home",
    about: "About the Dignity Initiative",
    "about.initiative": "The Dignity Research Initiative",
    "about.mission": "Mission & Vision",
    "about.fellows": "Participants",
    "about.participants": "Participants",
    "about.faculty": "Faculty",
    "about.researchers": "Researchers",
    "about.interns": "Interns",
    "about.students": "Students",
    "about.visitors": "Visitors",
    "about.partners": "Partners",
    projects: "Projects",
    "projects.research": "Research Projects",
    activities: "Activities",
    "activities.seminars": "Seminars",
    "activities.conferences": "Conferences",
    "activities.meetings": "Meetings",
    "activities.windsor": "The Windsor Birzeit Dignity Initiative",
    media: "Media & Updates",
    "media.news": "News",
    "media.announcements": "Announcements",
    "media.photos": "Photos",
    "media.clippings": "Clippings",
    "activities.research": "Research",
    "activities.research.dignityIssues": "Dignity Issues",
    "activities.research.dignityChildren": "Dignity of Children",
    "activities.research.ethics": "Research Ethics",
    "activities.research.arabRevolutions": "Arab Dignity Revolutions",
    "activities.research.decolonising": "Decolonising Knowledge Production",
    "activities.research.ai": "Artificial Intelligence",
    publications: "Publications",
    "publications.books": "Books",
    "publications.papers": "Papers",
    "publications.reports": "Reports",
    "publications.brochures": "Brochures",
    "publications.theses": "Theses",
    "publications.audiovisual": "Audiovisual",
    "publications.posters": "Posters",
    "publications.page.desc": "Books, papers, reports, and other publications produced by the Dignity initiative.",
    "publications.empty": "No publications available yet.",
    "publications.download": "Download",
    information: "Information",
    "information.readings": "Readings and Documents",
    "information.databases": "Databases",
    "information.page.desc": "Readings, documents, and databases relevant to the Dignity initiative's research.",
    "information.empty": "No items available yet.",
    "information.visit": "Visit",
    // HOME
    "hero.eyebrow": "Academic Initiative",
    "hero.title": "Advancing scholarship in service of human dignity.",
    "hero.desc": "Dignity brings together faculty, researchers, students, and partners to pursue rigorous inquiry, foster dialogue, and produce work of lasting public value.",
    "hero.btn.about": "About the Initiative",
    "hero.btn.research": "Our Research",
    "pillar.research": "Research",
    "pillar.research.desc": "Original inquiry across disciplines, from foundational scholarship to applied work.",
    "pillar.dialogue": "Dialogue",
    "pillar.dialogue.desc": "Seminars, conferences, and meetings that convene scholars and practitioners.",
    "pillar.partnership": "Partnership",
    "pillar.partnership.desc": "Collaboration with institutions worldwide, including The Windsor Birzeit Dignity Initiative.",
    "news.eyebrow": "Latest",
    "news.title": "News & Updates",
    "news.viewAll": "View all →",
    "news.prev": "Previous",
    "news.next": "Next",
    "news.readMore": "Read more",
    "news.collapse": "Collapse",
    "news.item1.date": "DEC 14 - JAN 2023",
    "news.item1.title": "Discussion of Raef Zreik's book / \"Kant's Struggle for Independence\"",
    "news.item1.excerpt": "The Karama Research Initiative at Birzeit University hosted Raef Zreik to present and discuss his latest book, published in mid-January by Lexington Publishing House.",
    "news.item2.date": "Placeholder date",
    "news.item2.title": "Article headline placeholder two",
    "news.item2.excerpt": "Brief summary of the second article will appear here once content is added.",
    "news.item3.date": "Placeholder date",
    "news.item3.title": "Article headline placeholder three",
    "news.item3.excerpt": "Brief summary of the third article will appear here once content is added.",
    // PAGE DESCRIPTIONS
    "page.placeholder": "This section is a placeholder. Replace this text with the official content for this page.",
    "page.placeholder2": "You can add multiple paragraphs, lists, images, and other elements here as the content becomes available.",
    "about.page.desc": "An overview of the Dignity initiative, its origins, and its scholarly purpose.",
    "mission.page.desc": "Our guiding mission and the vision that shapes our scholarly community.",
    "participants.page.desc": "The scholars, researchers, students, and visitors who form the Dignity community.",
    "partners.page.desc": "Institutions and organizations that collaborate with the Dignity initiative.",
    "projects.page.desc": "Active and recent research projects undertaken by members of the Dignity initiative.",
    "seminars.page.desc": "Information about Seminars organized through the Dignity initiative.",
    "conferences.page.desc": "Information about Conferences organized through the Dignity initiative.",
    "meetings.page.desc": "Information about Meetings organized through the Dignity initiative.",
    "windsor.page.desc": "Information about The Windsor Birzeit Dignity Initiative organized through the Dignity initiative.",
    "news.page.desc": "Latest news from the Dignity initiative.",
    "announcements.page.desc": "Latest announcements from the Dignity initiative.",
    "photos.page.desc": "Latest photos from the Dignity initiative.",
    "clippings.page.desc": "Latest clippings from the Dignity initiative.",
    // PARTICIPANTS
    "participants.select": "Select a category above to view participants.",
    "participants.name": "Name Placeholder",
    "participants.role": "Title / Role",
    "participants.bio": "Short biography placeholder. Add a brief description of this participant's background and contributions.",
    "participants.intro.faculty": "Placeholder introduction describing the faculty who participate in the Dignity initiative.",
    "participants.intro.researchers": "Placeholder introduction describing the researchers who participate in the Dignity initiative.",
    "participants.intro.interns": "Placeholder introduction describing the interns who participate in the Dignity initiative.",
    "participants.intro.students": "Placeholder introduction describing the students who participate in the Dignity initiative.",
    "participants.intro.visitors": "Placeholder introduction describing the visitors who participate in the Dignity initiative.",
    // PROJECTS
    "projects.area": "Research Area",
    "projects.placeholder.title": "Project Title Placeholder",
    "projects.placeholder.desc": "A short description of the project, its objectives, methodology, and expected outcomes will be added here.",
    // FOOTER
    "footer.about": "An academic initiative dedicated to research, dialogue, and human dignity.",
    "footer.explore": "Explore",
    "footer.participants": "Participants",
    "footer.contact": "Contact",
    "footer.university": "Birzeit University",
        "footer.pobox": "Room 5, Graduate Studies Building",
        "footer.zip": "P. O. Box 14, Birzeit, Palestine",
        "footer.phone": "Phone: +972 (2) 2982169",
        "footer.fax": "Fax: +972 (2) 2982168",
        "footer.email": "Email: Dignity@birzeit.edu",
    "footer.subscribe": "Subscribe to mailing list",
    "footer.subscribe.placeholder": "Your email address",
    "footer.subscribe.btn": "Subscribe",
    "footer.disclaimer": "Disclaimer",
    "footer.privacy": "Privacy Policy",
    "footer.sitemap": "Sitemap",
    "footer.copyright": "Copyright © Muwatin Institute for Democracy and Human Rights, 2019–2026.",
    "footer.resources": "Resources",
    "footer.studying": "Studying Materials",
    "footer.library": "Library",
    "footer.databases": "Databases",
    // TEAM SECTION
    "team.eyebrow": "Meet the Fellows",
    "team.title": "People driving our mission",
    "team.btn": "View All Fellows",
    "team.viewProfile": "View Profile",
    "team.name": "Dr. Name Placeholder",
    "team.role1": "Associate Professor",
    "team.role1b": "Research Lead",
    "team.role2": "Assistant Professor",
    "team.role2b": "Project Coordinator",
    "team.role3": "Assistant Professor",
    "team.role3b": "Researcher",
    // kept for compatibility
    "team.desc": "Researchers, faculty, and fellows whose work shapes the Dignity initiative.",
  },

  fr: {
    // NAV
    home: "Accueil",
    about: "À propos",
    "about.initiative": "À propos de l'initiative",
    "about.mission": "Mission et Vision",
    "about.participants": "Participants",
    "about.faculty": "Corps enseignant",
    "about.researchers": "Chercheurs",
    "about.interns": "Stagiaires",
    "about.students": "Étudiants",
    "about.visitors": "Visiteurs",
    "about.partners": "Partenaires",
    projects: "Projets",
    "projects.research": "Projets de recherche",
    activities: "Activités",
    "activities.seminars": "Séminaires",
    "activities.conferences": "Conférences",
    "activities.meetings": "Réunions",
    "activities.windsor": "Initiative Windsor-Birzeit",
    media: "Médias & mises à jour",
    "media.news": "Actualités",
    "media.announcements": "Annonces",
    "media.photos": "Photos",
    "media.clippings": "Revue de presse",
    // HOME
    "hero.eyebrow": "Initiative académique",
    "hero.title": "Faire avancer le savoir au service de la dignité humaine.",
    "hero.desc": "Dignity réunit des professeurs, chercheurs, étudiants et partenaires pour mener des recherches rigoureuses, favoriser le dialogue et produire des travaux de valeur publique durable.",
    "hero.btn.about": "À propos de l'initiative",
    "hero.btn.research": "Nos recherches",
    "pillar.research": "Recherche",
    "pillar.research.desc": "Enquête originale à travers les disciplines, de la recherche fondamentale au travail appliqué.",
    "pillar.dialogue": "Dialogue",
    "pillar.dialogue.desc": "Séminaires, conférences et réunions qui rassemblent chercheurs et praticiens.",
    "pillar.partnership": "Partenariat",
    "pillar.partnership.desc": "Collaboration avec des institutions du monde entier, notamment l'initiative Windsor-Birzeit.",
    "news.eyebrow": "Dernières nouvelles",
    "news.title": "Actualités et mises à jour",
    "news.viewAll": "Voir tout →",
    "news.prev": "Précédent",
    "news.next": "Suivant",
    "news.readMore": "Lire la suite",
    "news.collapse": "Réduire",
    "news.item1.date": "Date",
    "news.item1.title": "Titre du premier article",
    "news.item1.excerpt": "Un bref résumé du premier article apparaîtra ici une fois le contenu ajouté.",
    "news.item2.date": "Date",
    "news.item2.title": "Titre du deuxième article",
    "news.item2.excerpt": "Un bref résumé du deuxième article apparaîtra ici une fois le contenu ajouté.",
    "news.item3.date": "Date",
    "news.item3.title": "Titre du troisième article",
    "news.item3.excerpt": "Un bref résumé du troisième article apparaîtra ici une fois le contenu ajouté.",
    // PAGE DESCRIPTIONS
    "page.placeholder": "Cette section est un espace réservé. Remplacez ce texte par le contenu officiel de cette page.",
    "page.placeholder2": "Vous pouvez ajouter plusieurs paragraphes, listes, images et autres éléments ici une fois le contenu disponible.",
    "about.page.desc": "Un aperçu de l'initiative Dignity, ses origines et son objectif académique.",
    "mission.page.desc": "Notre mission directrice et la vision qui façonne notre communauté académique.",
    "participants.page.desc": "Les chercheurs, étudiants et visiteurs qui forment la communauté Dignity.",
    "partners.page.desc": "Institutions et organisations qui collaborent avec l'initiative Dignity.",
    "projects.page.desc": "Projets de recherche actifs et récents menés par les membres de l'initiative Dignity.",
    "seminars.page.desc": "Informations sur les séminaires organisés par l'initiative Dignity.",
    "conferences.page.desc": "Informations sur les conférences organisées par l'initiative Dignity.",
    "meetings.page.desc": "Informations sur les réunions organisées par l'initiative Dignity.",
    "windsor.page.desc": "Informations sur l'initiative Windsor-Birzeit organisée par l'initiative Dignity.",
    "news.page.desc": "Dernières nouvelles de l'initiative Dignity.",
    "announcements.page.desc": "Dernières annonces de l'initiative Dignity.",
    "photos.page.desc": "Dernières photos de l'initiative Dignity.",
    "clippings.page.desc": "Dernière revue de presse de l'initiative Dignity.",
    // PARTICIPANTS
    "participants.select": "Sélectionnez une catégorie ci-dessus pour voir les participants.",
    "participants.name": "Nom du participant",
    "participants.role": "Titre / Rôle",
    "participants.bio": "Courte biographie. Ajoutez une brève description de la formation et des contributions de ce participant.",
    "participants.intro.faculty": "Introduction décrivant les membres du corps enseignant qui participent à l'initiative Dignity.",
    "participants.intro.researchers": "Introduction décrivant les chercheurs qui participent à l'initiative Dignity.",
    "participants.intro.interns": "Introduction décrivant les stagiaires qui participent à l'initiative Dignity.",
    "participants.intro.students": "Introduction décrivant les étudiants qui participent à l'initiative Dignity.",
    "participants.intro.visitors": "Introduction décrivant les visiteurs qui participent à l'initiative Dignity.",
    // PROJECTS
    "projects.area": "Domaine de recherche",
    "projects.placeholder.title": "Titre du projet",
    "projects.placeholder.desc": "Une courte description du projet, ses objectifs, sa méthodologie et les résultats attendus seront ajoutés ici.",
    // FOOTER
    "footer.about": "Une initiative académique dédiée à la recherche, au dialogue et à la dignité humaine.",
    "footer.explore": "Explorer",
    "footer.participants": "Participants",
    "footer.contact": "Contact",
    "footer.university": "Université Birzeit",
        "footer.pobox": "Salle 5, Bâtiment des études supérieures",
        "footer.zip": "B.P. 14, Birzeit, Palestine",
        "footer.phone": "Tél. : +972 (2) 2982169",
        "footer.fax": "Fax : +972 (2) 2982168",
        "footer.email": "E-mail : Dignity@birzeit.edu",
    "footer.subscribe": "S'inscrire à la liste de diffusion",
    "footer.subscribe.placeholder": "Votre adresse e-mail",
    "footer.subscribe.btn": "S'inscrire",
    "footer.disclaimer": "Avertissement",
    "footer.privacy": "Politique de confidentialité",
    "footer.sitemap": "Plan du site",
    "footer.copyright": "Copyright © Institut Muwatin pour la Démocratie et les Droits de l'Homme, 2019–2026.",
    "footer.resources": "Ressources",
    "footer.studying": "Matériaux d'étude",
    "footer.library": "Bibliothèque",
    "footer.databases": "Bases de données",
    // TEAM SECTION
    "team.eyebrow": "L'équipe",
    "team.title": "Les personnes qui guident notre mission",
    "team.btn": "Voir tous les participants",
    "team.viewProfile": "Voir le profil",
    "team.name": "Dr. Nom ici",
    "team.role1": "Professeur associé",
    "team.role1b": "Responsable de recherche",
    "team.role2": "Maître de conférences",
    "team.role2b": "Coordinateur de projet",
    "team.role3": "Maître de conférences",
    "team.role3b": "Chercheur",
    "team.desc": "Chercheurs, professeurs et associés dont le travail façonne l'initiative Dignity.",
  },

  ar: {
    // NAV
    home: "الرئيسية",
    about: "عن مبادرة كرامة",
    "about.initiative": "مبادرة كرامة البحثية",
    "about.mission": "الرسالة والرؤية",
    "about.fellows": "المشاركون",
    "about.participants": "المشاركون",
    "about.faculty": "أعضاء هيئة التدريس",
    "about.researchers": "باحثون",
    "about.interns": "متدربون",
    "about.students": "طلاب",
    "about.visitors": "زائرون",
    "about.partners": "الشركاء",
    projects: "المشاريع",
    "projects.research": "المشاريع البحثية",
    activities: "الأنشطة",
    "activities.seminars": "ندوات",
    "activities.conferences": "المؤتمرات",
    "activities.meetings": "الاجتماعات",
    "activities.windsor": "مبادرة وندسور بيرزيت للكرامة",
    media: "الإعلام والتحديثات",
    "media.news": "أخبار",
    "media.announcements": "إعلانات",
    "media.photos": "صور",
    "media.clippings": "قصاصات",
    "activities.research": "أبحاث",
    "activities.research.dignityIssues": "قضايا الكرامة الإنسانية",
    "activities.research.dignityChildren": "كرامة الأطفال",
    "activities.research.ethics": "أخلاق البحث العلمي",
    "activities.research.arabRevolutions": "ثورات الكرامة العربية",
    "activities.research.decolonising": "نزع الاستعمار من عملية إنتاج المعرفة",
    "activities.research.ai": "الذكاء الاصطناعي",
    publications: "المنشورات",
    "publications.books": "كتب",
    "publications.papers": "أوراق بحثية",
    "publications.reports": "تقارير",
    "publications.brochures": "بروشورات",
    "publications.theses": "رسائل",
    "publications.audiovisual": "مرئي مسموع",
    "publications.posters": "ملصقات",
    "publications.page.desc": "كتب وأوراق بحثية وتقارير وغيرها من المنشورات الصادرة عن مبادرة الكرامة.",
    "publications.empty": "لا توجد منشورات متاحة حالياً.",
    "publications.download": "تحميل",
    information: "معلومات",
    "information.readings": "قراءات ووثائق",
    "information.databases": "قواعد معلومات",
    "information.page.desc": "قراءات ووثائق وقواعد معلومات ذات صلة بأبحاث مبادرة الكرامة.",
    "information.empty": "لا توجد عناصر متاحة حالياً.",
    "information.visit": "زيارة",
    // HOME
    "hero.eyebrow": "مبادرة أكاديمية",
    "hero.title": "تعزيز المعرفة في خدمة الكرامة الإنسانية.",
    "hero.desc": "تجمع مبادرة الكرامة أعضاء هيئة التدريس والباحثين والطلاب والشركاء لمتابعة البحث الصارم وتعزيز الحوار وإنتاج أعمال ذات قيمة عامة دائمة.",
    "hero.btn.about": "حول المبادرة",
    "hero.btn.research": "أبحاثنا",
    "pillar.research": "البحث",
    "pillar.research.desc": "استفسار أصيل عبر التخصصات، من الدراسة الأكاديمية الأساسية إلى العمل التطبيقي.",
    "pillar.dialogue": "الحوار",
    "pillar.dialogue.desc": "ندوات ومؤتمرات واجتماعات تجمع العلماء والممارسين.",
    "pillar.partnership": "الشراكة",
    "pillar.partnership.desc": "تعاون مع مؤسسات عالمية، بما فيها مبادرة وندسور بيرزيت للكرامة.",
    "news.eyebrow": "الأحدث",
    "news.title": "الأخبار والتحديثات",
    "news.viewAll": "← عرض الكل",
    "news.prev": "السابق",
    "news.next": "التالي",
    "news.readMore": "اقرأ المزيد",
    "news.collapse": "طيّ",
    "news.item1.date": "تاريخ",
    "news.item1.title": "عنوان المقال الأول",
    "news.item1.excerpt": "سيظهر هنا ملخص مختصر للمقال الأول بمجرد إضافة المحتوى.",
    "news.item2.date": "تاريخ",
    "news.item2.title": "عنوان المقال الثاني",
    "news.item2.excerpt": "سيظهر هنا ملخص مختصر للمقال الثاني بمجرد إضافة المحتوى.",
    "news.item3.date": "تاريخ",
    "news.item3.title": "عنوان المقال الثالث",
    "news.item3.excerpt": "سيظهر هنا ملخص مختصر للمقال الثالث بمجرد إضافة المحتوى.",
    // PAGE DESCRIPTIONS
    "page.placeholder": "هذا القسم عبارة عن نص تجريبي. استبدل هذا النص بالمحتوى الرسمي لهذه الصفحة.",
    "page.placeholder2": "يمكنك إضافة فقرات متعددة وقوائم وصور وعناصر أخرى هنا عند توفر المحتوى.",
    "about.page.desc": "نظرة عامة على مبادرة الكرامة وأصولها وغرضها الأكاديمي.",
    "mission.page.desc": "مهمتنا التوجيهية والرؤية التي تشكل مجتمعنا الأكاديمي.",
    "participants.page.desc": "العلماء والباحثون والطلاب والزوار الذين يشكلون مجتمع الكرامة.",
    "partners.page.desc": "المؤسسات والمنظمات التي تتعاون مع مبادرة الكرامة.",
    "projects.page.desc": "المشاريع البحثية النشطة والحديثة التي يضطلع بها أعضاء مبادرة الكرامة.",
    "seminars.page.desc": "معلومات حول الندوات المنظمة من خلال مبادرة الكرامة.",
    "conferences.page.desc": "معلومات حول المؤتمرات المنظمة من خلال مبادرة الكرامة.",
    "meetings.page.desc": "معلومات حول الاجتماعات المنظمة من خلال مبادرة الكرامة.",
    "windsor.page.desc": "معلومات حول مبادرة وندسور بيرزيت للكرامة المنظمة من خلال مبادرة الكرامة.",
    "news.page.desc": "آخر الأخبار من مبادرة الكرامة.",
    "announcements.page.desc": "آخر الإعلانات من مبادرة الكرامة.",
    "photos.page.desc": "آخر الصور من مبادرة الكرامة.",
    "clippings.page.desc": "آخر المقالات الصحفية من مبادرة الكرامة.",
    // PARTICIPANTS
    "participants.select": "اختر فئة من الأعلى لعرض المشاركين.",
    "participants.name": "اسم المشارك",
    "participants.role": "المسمى الوظيفي / الدور",
    "participants.bio": "نبذة مختصرة عن المشارك. أضف وصفاً مختصراً عن خلفية هذا المشارك ومساهماته.",
    "participants.intro.faculty": "نبذة تعريفية لأعضاء هيئة التدريس المشاركين في مبادرة الكرامة.",
    "participants.intro.researchers": "نبذة تعريفية للباحثين المشاركين في مبادرة الكرامة.",
    "participants.intro.interns": "نبذة تعريفية للمتدربين المشاركين في مبادرة الكرامة.",
    "participants.intro.students": "نبذة تعريفية للطلاب المشاركين في مبادرة الكرامة.",
    "participants.intro.visitors": "نبذة تعريفية للزوار المشاركين في مبادرة الكرامة.",
    // PROJECTS
    "projects.area": "مجال البحث",
    "projects.placeholder.title": "عنوان المشروع",
    "projects.placeholder.desc": "سيُضاف هنا وصف مختصر للمشروع وأهدافه ومنهجيته والنتائج المتوقعة.",
    // FOOTER
    "footer.about": "مبادرة أكاديمية مكرسة للبحث والحوار والكرامة الإنسانية.",
    "footer.explore": "استكشف",
    "footer.participants": "المشاركون",
    "footer.contact": "اتصل بنا",
    "footer.university": "جامعة بيرزيت",
        "footer.pobox": "غرفة 5، مبنى الدراسات العليا",
        "footer.zip": "ص.ب. 14، بيرزيت، فلسطين",
        "footer.phone": "هاتف: +972 (2) 2982169",
        "footer.fax": "فاكس: +972 (2) 2982168",
        "footer.email": "البريد الإلكتروني: Dignity@birzeit.edu",
    "footer.subscribe": "اشترك في القائمة البريدية",
    "footer.subscribe.placeholder": "عنوان بريدك الإلكتروني",
    "footer.subscribe.btn": "اشترك",
    "footer.disclaimer": "إخلاء المسؤولية",
    "footer.privacy": "سياسة الخصوصية",
    "footer.sitemap": "خريطة الموقع",
    "footer.copyright": "حقوق النشر © معهد مواطن للديمقراطية وحقوق الإنسان، 2019–2026.",
    "footer.resources": "الموارد",
    "footer.studying": "المواد الدراسية",
    "footer.library": "المكتبة",
    "footer.databases": "قواعد البيانات",
    // TEAM SECTION
    "team.eyebrow": "تعرف على الزملاء",
    "team.title": "الأشخاص الذين يقودون مهمتنا",
    "team.btn": "عرض جميع الزملاء",
    "team.viewProfile": "عرض الملف الشخصي",
    "team.name": "د. اسم المشارك",
    "team.role1": "أستاذ مشارك",
    "team.role1b": "مدير البحث",
    "team.role2": "أستاذ مساعد",
    "team.role2b": "منسق المشروع",
    "team.role3": "أستاذ مساعد",
    "team.role3b": "باحث",
    "team.desc": "الباحثون وأعضاء هيئة التدريس والزملاء الذين يشكّلون مبادرة الكرامة.",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

// Maps translation keys to the corresponding Site Settings field name (English base;
// the Arabic value lives at `${base}Ar`). Only keys editable via Payload appear here --
// anything absent falls back to the hardcoded dictionary above untouched.
const SITE_SETTINGS_KEY_MAP: Partial<Record<TranslationKey, string>> = {
    home: "navHome",
    about: "navAbout",
    "about.initiative": "navAboutInitiative",
    "about.mission": "navAboutMission",
    "about.fellows": "navAboutFellows",
    "about.participants": "navAboutFellows",
    "about.partners": "navAboutPartners",
    projects: "navProjects",
    "projects.research": "navProjectsResearch",
    activities: "navActivities",
    "activities.seminars": "navActivitiesSeminars",
    "activities.conferences": "navActivitiesConferences",
    "activities.meetings": "navActivitiesMeetings",
    "activities.windsor": "navActivitiesWindsor",
    media: "navMedia",
    "media.news": "navMediaNews",
    "media.announcements": "navMediaAnnouncements",
    "media.photos": "navMediaPhotos",
    "media.clippings": "navMediaClippings",

    "hero.eyebrow": "heroEyebrow",
    "hero.title": "heroTitle",
    "hero.desc": "heroDesc",
    "hero.btn.about": "heroBtnAbout",
    "hero.btn.research": "heroBtnResearch",
    "pillar.research": "pillarResearch",
    "pillar.research.desc": "pillarResearchDesc",
    "pillar.dialogue": "pillarDialogue",
    "pillar.dialogue.desc": "pillarDialogueDesc",
    "pillar.partnership": "pillarPartnership",
    "pillar.partnership.desc": "pillarPartnershipDesc",
    "news.viewAll": "newsViewAll",
    "news.prev": "newsPrev",
    "news.next": "newsNext",
    "news.readMore": "newsReadMore",
    "news.collapse": "newsCollapse",

    "footer.about": "footerAbout",
    "footer.explore": "footerExplore",
    "footer.participants": "footerParticipants",
    "footer.contact": "footerContact",
    "footer.university": "footerUniversity",
    "footer.pobox": "footerPobox",
    "footer.zip": "footerZip",
    "footer.phone": "footerPhone",
    "footer.fax": "footerFax",
    "footer.email": "footerEmail",
    "footer.subscribe": "footerSubscribe",
    "footer.subscribe.placeholder": "footerSubscribePlaceholder",
    "footer.subscribe.btn": "footerSubscribeBtn",
    "footer.disclaimer": "footerDisclaimer",
    "footer.privacy": "footerPrivacy",
    "footer.sitemap": "footerSitemap",
    "footer.copyright": "footerCopyright",
    "footer.resources": "footerResources",
    "footer.studying": "footerStudying",
    "footer.library": "footerLibrary",
    "footer.databases": "footerDatabases",

    "team.eyebrow": "teamEyebrow",
    "team.title": "teamTitle",
    "team.btn": "teamBtn",

    "projects.area": "projectsArea",
};

const LanguageContext = createContext<LanguageContextValue>({} as LanguageContextValue);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>("ar");
  const dir = lang === "ar" ? "rtl" : "ltr";
  const isArabic = lang === "ar";
    const [overrides, setOverrides] = useState<PayloadSiteSettings | null>(null);

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
    if (isArabic) {
      document.documentElement.classList.add("lang-ar");
    } else {
      document.documentElement.classList.remove("lang-ar");
    }
  }, [lang, dir, isArabic]);

    useEffect(() => {
          let cancelled = false;
          fetchSiteSettings().then((data) => {
                  if (!cancelled && data) setOverrides(data);
          });
          return () => {
                  cancelled = true;
          };
    }, []);

const t = (key: TranslationKey) => {
      const base = SITE_SETTINGS_KEY_MAP[key];
      if (base && overrides) {
              const value = overrides[isArabic ? `${base}Ar` : base];
              if (value) return value;
      }
      return translations[lang][key];
};

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir, isArabic }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
