/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    activities: Activity;
    'media-updates': MediaUpdate;
    participants: Participant;
    publications: Publication;
    information: Information;
    'research-activities': ResearchActivity;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'media-updates': MediaUpdatesSelect<false> | MediaUpdatesSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    information: InformationSelect<false> | InformationSelect<true>;
    'research-activities': ResearchActivitiesSelect<false> | ResearchActivitiesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'content-manager' | 'editor';
  /**
   * The sections this editor is allowed to manage.
   */
  section?:
    | (
        | 'articles'
        | 'activities'
        | 'media'
        | 'participants'
        | 'publications'
        | 'information'
        | 'research'
        | 'pages'
        | 'site-settings'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  titleAr?: string | null;
  date: string;
  excerpt?: string | null;
  excerptAr?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  title: string;
  titleAr?: string | null;
  type: 'seminar' | 'conference' | 'meeting' | 'windsor-birzeit';
  date: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-updates".
 */
export interface MediaUpdate {
  id: string;
  title: string;
  titleAr?: string | null;
  type: 'news' | 'announcement' | 'photo' | 'clipping';
  date: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: string;
  name: string;
  nameAr?: string | null;
  category: 'faculty' | 'researcher' | 'intern' | 'student' | 'visitor';
  title?: string | null;
  titleAr?: string | null;
  email?: string | null;
  bio?: string | null;
  bioAr?: string | null;
  photo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: string;
  title: string;
  titleAr?: string | null;
  type: 'books' | 'papers' | 'reports' | 'brochures' | 'theses' | 'audiovisual' | 'posters';
  author?: string | null;
  authorAr?: string | null;
  date: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  file?: (string | null) | Media;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "information".
 */
export interface Information {
  id: string;
  title: string;
  titleAr?: string | null;
  type: 'readings-documents' | 'databases';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link?: string | null;
  file?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-activities".
 */
export interface ResearchActivity {
  id: string;
  title: string;
  titleAr?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  slug: string;
  title?: string | null;
  titleAr?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bodyAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'media-updates';
        value: string | MediaUpdate;
      } | null)
    | ({
        relationTo: 'participants';
        value: string | Participant;
      } | null)
    | ({
        relationTo: 'publications';
        value: string | Publication;
      } | null)
    | ({
        relationTo: 'information';
        value: string | Information;
      } | null)
    | ({
        relationTo: 'research-activities';
        value: string | ResearchActivity;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  section?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  excerpt?: T;
  excerptAr?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  type?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-updates_select".
 */
export interface MediaUpdatesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  type?: T;
  date?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  name?: T;
  nameAr?: T;
  category?: T;
  title?: T;
  titleAr?: T;
  email?: T;
  bio?: T;
  bioAr?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  type?: T;
  author?: T;
  authorAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  file?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "information_select".
 */
export interface InformationSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  type?: T;
  description?: T;
  descriptionAr?: T;
  link?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-activities_select".
 */
export interface ResearchActivitiesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  body?: T;
  bodyAr?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  navHome?: string | null;
  navHomeAr?: string | null;
  navAbout?: string | null;
  navAboutAr?: string | null;
  navAboutInitiative?: string | null;
  navAboutInitiativeAr?: string | null;
  navAboutMission?: string | null;
  navAboutMissionAr?: string | null;
  navAboutFellows?: string | null;
  navAboutFellowsAr?: string | null;
  navAboutPartners?: string | null;
  navAboutPartnersAr?: string | null;
  navProjects?: string | null;
  navProjectsAr?: string | null;
  navProjectsResearch?: string | null;
  navProjectsResearchAr?: string | null;
  navActivities?: string | null;
  navActivitiesAr?: string | null;
  navActivitiesSeminars?: string | null;
  navActivitiesSeminarsAr?: string | null;
  navActivitiesConferences?: string | null;
  navActivitiesConferencesAr?: string | null;
  navActivitiesMeetings?: string | null;
  navActivitiesMeetingsAr?: string | null;
  navActivitiesWindsor?: string | null;
  navActivitiesWindsorAr?: string | null;
  navMedia?: string | null;
  navMediaAr?: string | null;
  navMediaNews?: string | null;
  navMediaNewsAr?: string | null;
  navMediaAnnouncements?: string | null;
  navMediaAnnouncementsAr?: string | null;
  navMediaPhotos?: string | null;
  navMediaPhotosAr?: string | null;
  navMediaClippings?: string | null;
  navMediaClippingsAr?: string | null;
  heroEyebrow?: string | null;
  heroEyebrowAr?: string | null;
  heroTitle?: string | null;
  heroTitleAr?: string | null;
  heroDesc?: string | null;
  heroDescAr?: string | null;
  heroBtnAbout?: string | null;
  heroBtnAboutAr?: string | null;
  heroBtnResearch?: string | null;
  heroBtnResearchAr?: string | null;
  pillarResearch?: string | null;
  pillarResearchAr?: string | null;
  pillarResearchDesc?: string | null;
  pillarResearchDescAr?: string | null;
  pillarDialogue?: string | null;
  pillarDialogueAr?: string | null;
  pillarDialogueDesc?: string | null;
  pillarDialogueDescAr?: string | null;
  pillarPartnership?: string | null;
  pillarPartnershipAr?: string | null;
  pillarPartnershipDesc?: string | null;
  pillarPartnershipDescAr?: string | null;
  teamEyebrow?: string | null;
  teamEyebrowAr?: string | null;
  teamTitle?: string | null;
  teamTitleAr?: string | null;
  teamBtn?: string | null;
  teamBtnAr?: string | null;
  newsViewAll?: string | null;
  newsViewAllAr?: string | null;
  footerAbout?: string | null;
  footerAboutAr?: string | null;
  footerExplore?: string | null;
  footerExploreAr?: string | null;
  footerParticipants?: string | null;
  footerParticipantsAr?: string | null;
  footerContact?: string | null;
  footerContactAr?: string | null;
  footerUniversity?: string | null;
  footerUniversityAr?: string | null;
  footerPobox?: string | null;
  footerPoboxAr?: string | null;
  footerZip?: string | null;
  footerZipAr?: string | null;
  footerPhone?: string | null;
  footerPhoneAr?: string | null;
  footerFax?: string | null;
  footerFaxAr?: string | null;
  footerEmail?: string | null;
  footerEmailAr?: string | null;
  footerSubscribe?: string | null;
  footerSubscribeAr?: string | null;
  footerSubscribePlaceholder?: string | null;
  footerSubscribePlaceholderAr?: string | null;
  footerSubscribeBtn?: string | null;
  footerSubscribeBtnAr?: string | null;
  footerDisclaimer?: string | null;
  footerDisclaimerAr?: string | null;
  footerPrivacy?: string | null;
  footerPrivacyAr?: string | null;
  footerSitemap?: string | null;
  footerSitemapAr?: string | null;
  footerCopyright?: string | null;
  footerCopyrightAr?: string | null;
  footerResources?: string | null;
  footerResourcesAr?: string | null;
  footerStudying?: string | null;
  footerStudyingAr?: string | null;
  footerLibrary?: string | null;
  footerLibraryAr?: string | null;
  footerDatabases?: string | null;
  footerDatabasesAr?: string | null;
  newsPrev?: string | null;
  newsPrevAr?: string | null;
  newsNext?: string | null;
  newsNextAr?: string | null;
  newsReadMore?: string | null;
  newsReadMoreAr?: string | null;
  newsCollapse?: string | null;
  newsCollapseAr?: string | null;
  projectsArea?: string | null;
  projectsAreaAr?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  navHome?: T;
  navHomeAr?: T;
  navAbout?: T;
  navAboutAr?: T;
  navAboutInitiative?: T;
  navAboutInitiativeAr?: T;
  navAboutMission?: T;
  navAboutMissionAr?: T;
  navAboutFellows?: T;
  navAboutFellowsAr?: T;
  navAboutPartners?: T;
  navAboutPartnersAr?: T;
  navProjects?: T;
  navProjectsAr?: T;
  navProjectsResearch?: T;
  navProjectsResearchAr?: T;
  navActivities?: T;
  navActivitiesAr?: T;
  navActivitiesSeminars?: T;
  navActivitiesSeminarsAr?: T;
  navActivitiesConferences?: T;
  navActivitiesConferencesAr?: T;
  navActivitiesMeetings?: T;
  navActivitiesMeetingsAr?: T;
  navActivitiesWindsor?: T;
  navActivitiesWindsorAr?: T;
  navMedia?: T;
  navMediaAr?: T;
  navMediaNews?: T;
  navMediaNewsAr?: T;
  navMediaAnnouncements?: T;
  navMediaAnnouncementsAr?: T;
  navMediaPhotos?: T;
  navMediaPhotosAr?: T;
  navMediaClippings?: T;
  navMediaClippingsAr?: T;
  heroEyebrow?: T;
  heroEyebrowAr?: T;
  heroTitle?: T;
  heroTitleAr?: T;
  heroDesc?: T;
  heroDescAr?: T;
  heroBtnAbout?: T;
  heroBtnAboutAr?: T;
  heroBtnResearch?: T;
  heroBtnResearchAr?: T;
  pillarResearch?: T;
  pillarResearchAr?: T;
  pillarResearchDesc?: T;
  pillarResearchDescAr?: T;
  pillarDialogue?: T;
  pillarDialogueAr?: T;
  pillarDialogueDesc?: T;
  pillarDialogueDescAr?: T;
  pillarPartnership?: T;
  pillarPartnershipAr?: T;
  pillarPartnershipDesc?: T;
  pillarPartnershipDescAr?: T;
  teamEyebrow?: T;
  teamEyebrowAr?: T;
  teamTitle?: T;
  teamTitleAr?: T;
  teamBtn?: T;
  teamBtnAr?: T;
  newsViewAll?: T;
  newsViewAllAr?: T;
  footerAbout?: T;
  footerAboutAr?: T;
  footerExplore?: T;
  footerExploreAr?: T;
  footerParticipants?: T;
  footerParticipantsAr?: T;
  footerContact?: T;
  footerContactAr?: T;
  footerUniversity?: T;
  footerUniversityAr?: T;
  footerPobox?: T;
  footerPoboxAr?: T;
  footerZip?: T;
  footerZipAr?: T;
  footerPhone?: T;
  footerPhoneAr?: T;
  footerFax?: T;
  footerFaxAr?: T;
  footerEmail?: T;
  footerEmailAr?: T;
  footerSubscribe?: T;
  footerSubscribeAr?: T;
  footerSubscribePlaceholder?: T;
  footerSubscribePlaceholderAr?: T;
  footerSubscribeBtn?: T;
  footerSubscribeBtnAr?: T;
  footerDisclaimer?: T;
  footerDisclaimerAr?: T;
  footerPrivacy?: T;
  footerPrivacyAr?: T;
  footerSitemap?: T;
  footerSitemapAr?: T;
  footerCopyright?: T;
  footerCopyrightAr?: T;
  footerResources?: T;
  footerResourcesAr?: T;
  footerStudying?: T;
  footerStudyingAr?: T;
  footerLibrary?: T;
  footerLibraryAr?: T;
  footerDatabases?: T;
  footerDatabasesAr?: T;
  newsPrev?: T;
  newsPrevAr?: T;
  newsNext?: T;
  newsNextAr?: T;
  newsReadMore?: T;
  newsReadMoreAr?: T;
  newsCollapse?: T;
  newsCollapseAr?: T;
  projectsArea?: T;
  projectsAreaAr?: T;
  updatedAt?: T;
  createdAt?: T;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
