/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'about-initiative': AboutInitiative;
    participants: Participant;
    news: News;
    announcements: Announcement;
    photos: Photo;
    clippings: Clipping;
    partners: Partner;
    research: Research;
    seminars: Seminar;
    conferences: Conference;
    meetings: Meeting;
    'windsor-dignity': WindsorDignity;
    books: Book;
    papers: Paper;
    reports: Report;
    brochures: Brochure;
    theses: Thesis;
    audiovisual: Audiovisual;
    posters: Poster;
    'readings-documents': ReadingsDocument;
    databases: Database;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'about-initiative': AboutInitiativeSelect<false> | AboutInitiativeSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    clippings: ClippingsSelect<false> | ClippingsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    seminars: SeminarsSelect<false> | SeminarsSelect<true>;
    conferences: ConferencesSelect<false> | ConferencesSelect<true>;
    meetings: MeetingsSelect<false> | MeetingsSelect<true>;
    'windsor-dignity': WindsorDignitySelect<false> | WindsorDignitySelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    papers: PapersSelect<false> | PapersSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    brochures: BrochuresSelect<false> | BrochuresSelect<true>;
    theses: ThesesSelect<false> | ThesesSelect<true>;
    audiovisual: AudiovisualSelect<false> | AudiovisualSelect<true>;
    posters: PostersSelect<false> | PostersSelect<true>;
    'readings-documents': ReadingsDocumentsSelect<false> | ReadingsDocumentsSelect<true>;
    databases: DatabasesSelect<false> | DatabasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Content Managers can manage Users and Pages. Editors can create/edit/delete everything else.
   */
  role: 'content-manager' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * All uploaded images and files across the whole site live here. You usually don't need to open this directly — upload from the "Image" or "File" field on the entry you're editing instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Auto-generated preview image (page 1) for PDF uploads. Left empty for non-PDF files.
   */
  thumbnail?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The heading, intro and full text of the website's "The Dignity Research Initiative" page. Open the entry below to edit it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-initiative".
 */
export interface AboutInitiative {
  id: string;
  title?: string | null;
  titleAr?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bodyAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under About the Dignity Initiative → Participants. Add a new entry here for each person.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: string;
  name: string;
  nameAr: string;
  category: 'faculty' | 'researcher' | 'intern' | 'student' | 'visitor';
  title?: string | null;
  titleAr?: string | null;
  email?: string | null;
  bio?: string | null;
  bioAr?: string | null;
  photo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Add a new entry here for each news post.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  titleAr: string;
  date: string;
  excerpt?: string | null;
  excerptAr?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under About the Dignity Initiative → Announcements. Add a new entry here for each announcement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  title: string;
  titleAr: string;
  date: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under About the Dignity Initiative → Photos. Upload one photo per entry (click the Image field below to upload).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: string;
  /**
   * A short caption for this photo, e.g. "Seminar on Dignity and Praxis, March 2026".
   */
  title: string;
  titleAr: string;
  date: string;
  image: string | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under About the Dignity Initiative → Clippings (press mentions, newspaper scans, etc). Upload a scanned image of the clipping in the Image field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clippings".
 */
export interface Clipping {
  id: string;
  /**
   * The headline or name of the publication this clipping is from.
   */
  title: string;
  titleAr: string;
  date: string;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The heading, intro and full text of the website's Partners page. Open the entry below to edit it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  title?: string | null;
  titleAr?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bodyAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Activities → Research. Each entry gets its own page, where the publications, clippings and photos selected below appear alongside it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: string;
  title: string;
  titleAr: string;
  description?: string | null;
  descriptionAr?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  /**
   * Filled in automatically from the English title. It is the end of this entry's web address, so changing it after the page has been shared will break the old link.
   */
  slug?: string | null;
  /**
   * Select existing books or add new ones.
   */
  relatedBooks?: (string | Book)[] | null;
  relatedPapers?: (string | Paper)[] | null;
  relatedReports?: (string | Report)[] | null;
  relatedBrochures?: (string | Brochure)[] | null;
  relatedTheses?: (string | Thesis)[] | null;
  relatedAudiovisual?: (string | Audiovisual)[] | null;
  relatedPosters?: (string | Poster)[] | null;
  relatedClippings?: (string | Clipping)[] | null;
  relatedPhotos?: (string | Photo)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Publications → Books.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: string;
  title: string;
  titleAr: string;
  author?: string | null;
  authorAr?: string | null;
  date?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  file?: (string | null) | Media;
  /**
   * Use for items that live elsewhere rather than as an uploaded file — a YouTube video, for example. Leave empty when a file is attached above.
   */
  link?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Publications → Papers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "papers".
 */
export interface Paper {
  id: string;
  title: string;
  titleAr: string;
  author?: string | null;
  authorAr?: string | null;
  date?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  file?: (string | null) | Media;
  /**
   * Use for items that live elsewhere rather than as an uploaded file — a YouTube video, for example. Leave empty when a file is attached above.
   */
  link?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Publications → Reports.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  title: string;
  titleAr: string;
  author?: string | null;
  authorAr?: string | null;
  date?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  file?: (string | null) | Media;
  /**
   * Use for items that live elsewhere rather than as an uploaded file — a YouTube video, for example. Leave empty when a file is attached above.
   */
  link?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Publications → Brochures.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brochures".
 */
export interface Brochure {
  id: string;
  title: string;
  titleAr: string;
  author?: string | null;
  authorAr?: string | null;
  date?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  file?: (string | null) | Media;
  /**
   * Use for items that live elsewhere rather than as an uploaded file — a YouTube video, for example. Leave empty when a file is attached above.
   */
  link?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Publications → Theses.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theses".
 */
export interface Thesis {
  id: string;
  title: string;
  titleAr: string;
  author?: string | null;
  authorAr?: string | null;
  date?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  file?: (string | null) | Media;
  /**
   * Use for items that live elsewhere rather than as an uploaded file — a YouTube video, for example. Leave empty when a file is attached above.
   */
  link?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Publications → Audiovisual. Videos are usually a link rather than an upload.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audiovisual".
 */
export interface Audiovisual {
  id: string;
  title: string;
  titleAr: string;
  author?: string | null;
  authorAr?: string | null;
  date?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  file?: (string | null) | Media;
  /**
   * Use for items that live elsewhere rather than as an uploaded file — a YouTube video, for example. Leave empty when a file is attached above.
   */
  link?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Publications → Posters.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posters".
 */
export interface Poster {
  id: string;
  title: string;
  titleAr: string;
  author?: string | null;
  authorAr?: string | null;
  date?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  file?: (string | null) | Media;
  /**
   * Use for items that live elsewhere rather than as an uploaded file — a YouTube video, for example. Leave empty when a file is attached above.
   */
  link?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Seminars organized through the Dignity initiative.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seminars".
 */
export interface Seminar {
  id: string;
  title: string;
  titleAr: string;
  date: string;
  description?: string | null;
  descriptionAr?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Conferences organized through the Dignity initiative.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conferences".
 */
export interface Conference {
  id: string;
  title: string;
  titleAr: string;
  date: string;
  description?: string | null;
  descriptionAr?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Meetings organized through the Dignity initiative.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meetings".
 */
export interface Meeting {
  id: string;
  title: string;
  titleAr: string;
  date: string;
  description?: string | null;
  descriptionAr?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  /**
   * Additional photographs for this meeting. They appear only inside the meeting, after a visitor opens it.
   */
  gallery?:
    | {
        image: string | Media;
        caption?: string | null;
        captionAr?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Windsor Birzeit Dignity Initiative events, activities, and information.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "windsor-dignity".
 */
export interface WindsorDignity {
  id: string;
  title: string;
  titleAr: string;
  date?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Information → Readings and Documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "readings-documents".
 */
export interface ReadingsDocument {
  id: string;
  title: string;
  titleAr: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link?: string | null;
  file?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shows on the website under Information → Databases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "databases".
 */
export interface Database {
  id: string;
  title: string;
  titleAr: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link?: string | null;
  file?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'about-initiative';
        value: string | AboutInitiative;
      } | null)
    | ({
        relationTo: 'participants';
        value: string | Participant;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'photos';
        value: string | Photo;
      } | null)
    | ({
        relationTo: 'clippings';
        value: string | Clipping;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'research';
        value: string | Research;
      } | null)
    | ({
        relationTo: 'seminars';
        value: string | Seminar;
      } | null)
    | ({
        relationTo: 'conferences';
        value: string | Conference;
      } | null)
    | ({
        relationTo: 'meetings';
        value: string | Meeting;
      } | null)
    | ({
        relationTo: 'windsor-dignity';
        value: string | WindsorDignity;
      } | null)
    | ({
        relationTo: 'books';
        value: string | Book;
      } | null)
    | ({
        relationTo: 'papers';
        value: string | Paper;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'brochures';
        value: string | Brochure;
      } | null)
    | ({
        relationTo: 'theses';
        value: string | Thesis;
      } | null)
    | ({
        relationTo: 'audiovisual';
        value: string | Audiovisual;
      } | null)
    | ({
        relationTo: 'posters';
        value: string | Poster;
      } | null)
    | ({
        relationTo: 'readings-documents';
        value: string | ReadingsDocument;
      } | null)
    | ({
        relationTo: 'databases';
        value: string | Database;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-initiative_select".
 */
export interface AboutInitiativeSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  body?: T;
  bodyAr?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  name?: T;
  nameAr?: T;
  category?: T;
  title?: T;
  titleAr?: T;
  email?: T;
  bio?: T;
  bioAr?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  excerpt?: T;
  excerptAr?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clippings_select".
 */
export interface ClippingsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  body?: T;
  bodyAr?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  slug?: T;
  relatedBooks?: T;
  relatedPapers?: T;
  relatedReports?: T;
  relatedBrochures?: T;
  relatedTheses?: T;
  relatedAudiovisual?: T;
  relatedPosters?: T;
  relatedClippings?: T;
  relatedPhotos?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seminars_select".
 */
export interface SeminarsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conferences_select".
 */
export interface ConferencesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meetings_select".
 */
export interface MeetingsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        captionAr?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "windsor-dignity_select".
 */
export interface WindsorDignitySelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  content?: T;
  contentAr?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  author?: T;
  authorAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  file?: T;
  link?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "papers_select".
 */
export interface PapersSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  author?: T;
  authorAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  file?: T;
  link?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  author?: T;
  authorAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  file?: T;
  link?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brochures_select".
 */
export interface BrochuresSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  author?: T;
  authorAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  file?: T;
  link?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theses_select".
 */
export interface ThesesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  author?: T;
  authorAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  file?: T;
  link?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audiovisual_select".
 */
export interface AudiovisualSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  author?: T;
  authorAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  file?: T;
  link?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posters_select".
 */
export interface PostersSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  author?: T;
  authorAr?: T;
  date?: T;
  description?: T;
  descriptionAr?: T;
  file?: T;
  link?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "readings-documents_select".
 */
export interface ReadingsDocumentsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  link?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "databases_select".
 */
export interface DatabasesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  link?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide text: navigation menu, homepage hero, footer, and small UI labels. Editing a field here updates it everywhere it appears on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  navAbout?: string | null;
  navAboutAr?: string | null;
  navAboutInitiative?: string | null;
  navAboutInitiativeAr?: string | null;
  navAboutFellows?: string | null;
  navAboutFellowsAr?: string | null;
  navMediaNews?: string | null;
  navMediaNewsAr?: string | null;
  navMediaAnnouncements?: string | null;
  navMediaAnnouncementsAr?: string | null;
  navMediaPhotos?: string | null;
  navMediaPhotosAr?: string | null;
  navMediaClippings?: string | null;
  navMediaClippingsAr?: string | null;
  navAboutPartners?: string | null;
  navAboutPartnersAr?: string | null;
  navActivities?: string | null;
  navActivitiesAr?: string | null;
  navProjectsResearch?: string | null;
  navProjectsResearchAr?: string | null;
  navActivitiesSeminars?: string | null;
  navActivitiesSeminarsAr?: string | null;
  navActivitiesConferences?: string | null;
  navActivitiesConferencesAr?: string | null;
  navActivitiesMeetings?: string | null;
  navActivitiesMeetingsAr?: string | null;
  navActivitiesWindsor?: string | null;
  navActivitiesWindsorAr?: string | null;
  navPublications?: string | null;
  navPublicationsAr?: string | null;
  navPublicationsBooks?: string | null;
  navPublicationsBooksAr?: string | null;
  navPublicationsPapers?: string | null;
  navPublicationsPapersAr?: string | null;
  navPublicationsReports?: string | null;
  navPublicationsReportsAr?: string | null;
  navPublicationsBrochures?: string | null;
  navPublicationsBrochuresAr?: string | null;
  navPublicationsTheses?: string | null;
  navPublicationsThesesAr?: string | null;
  navPublicationsAudiovisual?: string | null;
  navPublicationsAudiovisualAr?: string | null;
  navPublicationsPosters?: string | null;
  navPublicationsPostersAr?: string | null;
  navInformation?: string | null;
  navInformationAr?: string | null;
  navInformationReadings?: string | null;
  navInformationReadingsAr?: string | null;
  navInformationDatabases?: string | null;
  navInformationDatabasesAr?: string | null;
  heroEyebrow?: string | null;
  heroEyebrowAr?: string | null;
  heroTitle?: string | null;
  heroTitleAr?: string | null;
  heroDesc?: string | null;
  heroDescAr?: string | null;
  heroBtnAbout?: string | null;
  heroBtnAboutAr?: string | null;
  heroBtnResearch?: string | null;
  heroBtnResearchAr?: string | null;
  pillarResearch?: string | null;
  pillarResearchAr?: string | null;
  pillarResearchDesc?: string | null;
  pillarResearchDescAr?: string | null;
  pillarDialogue?: string | null;
  pillarDialogueAr?: string | null;
  pillarDialogueDesc?: string | null;
  pillarDialogueDescAr?: string | null;
  pillarPartnership?: string | null;
  pillarPartnershipAr?: string | null;
  pillarPartnershipDesc?: string | null;
  pillarPartnershipDescAr?: string | null;
  teamEyebrow?: string | null;
  teamEyebrowAr?: string | null;
  teamTitle?: string | null;
  teamTitleAr?: string | null;
  teamBtn?: string | null;
  teamBtnAr?: string | null;
  newsViewAll?: string | null;
  newsViewAllAr?: string | null;
  footerAbout?: string | null;
  footerAboutAr?: string | null;
  footerExplore?: string | null;
  footerExploreAr?: string | null;
  footerParticipants?: string | null;
  footerParticipantsAr?: string | null;
  footerContact?: string | null;
  footerContactAr?: string | null;
  footerUniversity?: string | null;
  footerUniversityAr?: string | null;
  footerPobox?: string | null;
  footerPoboxAr?: string | null;
  footerZip?: string | null;
  footerZipAr?: string | null;
  footerPhone?: string | null;
  footerPhoneAr?: string | null;
  footerFax?: string | null;
  footerFaxAr?: string | null;
  footerEmail?: string | null;
  footerEmailAr?: string | null;
  footerSubscribe?: string | null;
  footerSubscribeAr?: string | null;
  footerSubscribePlaceholder?: string | null;
  footerSubscribePlaceholderAr?: string | null;
  footerSubscribeBtn?: string | null;
  footerSubscribeBtnAr?: string | null;
  footerDisclaimer?: string | null;
  footerDisclaimerAr?: string | null;
  footerPrivacy?: string | null;
  footerPrivacyAr?: string | null;
  footerSitemap?: string | null;
  footerSitemapAr?: string | null;
  footerCopyright?: string | null;
  footerCopyrightAr?: string | null;
  footerResources?: string | null;
  footerResourcesAr?: string | null;
  footerStudying?: string | null;
  footerStudyingAr?: string | null;
  footerLibrary?: string | null;
  footerLibraryAr?: string | null;
  footerDatabases?: string | null;
  footerDatabasesAr?: string | null;
  newsPrev?: string | null;
  newsPrevAr?: string | null;
  newsNext?: string | null;
  newsNextAr?: string | null;
  newsReadMore?: string | null;
  newsReadMoreAr?: string | null;
  newsCollapse?: string | null;
  newsCollapseAr?: string | null;
  projectsArea?: string | null;
  projectsAreaAr?: string | null;
  navMedia?: string | null;
  navMediaAr?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  navAbout?: T;
  navAboutAr?: T;
  navAboutInitiative?: T;
  navAboutInitiativeAr?: T;
  navAboutFellows?: T;
  navAboutFellowsAr?: T;
  navMediaNews?: T;
  navMediaNewsAr?: T;
  navMediaAnnouncements?: T;
  navMediaAnnouncementsAr?: T;
  navMediaPhotos?: T;
  navMediaPhotosAr?: T;
  navMediaClippings?: T;
  navMediaClippingsAr?: T;
  navAboutPartners?: T;
  navAboutPartnersAr?: T;
  navActivities?: T;
  navActivitiesAr?: T;
  navProjectsResearch?: T;
  navProjectsResearchAr?: T;
  navActivitiesSeminars?: T;
  navActivitiesSeminarsAr?: T;
  navActivitiesConferences?: T;
  navActivitiesConferencesAr?: T;
  navActivitiesMeetings?: T;
  navActivitiesMeetingsAr?: T;
  navActivitiesWindsor?: T;
  navActivitiesWindsorAr?: T;
  navPublications?: T;
  navPublicationsAr?: T;
  navPublicationsBooks?: T;
  navPublicationsBooksAr?: T;
  navPublicationsPapers?: T;
  navPublicationsPapersAr?: T;
  navPublicationsReports?: T;
  navPublicationsReportsAr?: T;
  navPublicationsBrochures?: T;
  navPublicationsBrochuresAr?: T;
  navPublicationsTheses?: T;
  navPublicationsThesesAr?: T;
  navPublicationsAudiovisual?: T;
  navPublicationsAudiovisualAr?: T;
  navPublicationsPosters?: T;
  navPublicationsPostersAr?: T;
  navInformation?: T;
  navInformationAr?: T;
  navInformationReadings?: T;
  navInformationReadingsAr?: T;
  navInformationDatabases?: T;
  navInformationDatabasesAr?: T;
  heroEyebrow?: T;
  heroEyebrowAr?: T;
  heroTitle?: T;
  heroTitleAr?: T;
  heroDesc?: T;
  heroDescAr?: T;
  heroBtnAbout?: T;
  heroBtnAboutAr?: T;
  heroBtnResearch?: T;
  heroBtnResearchAr?: T;
  pillarResearch?: T;
  pillarResearchAr?: T;
  pillarResearchDesc?: T;
  pillarResearchDescAr?: T;
  pillarDialogue?: T;
  pillarDialogueAr?: T;
  pillarDialogueDesc?: T;
  pillarDialogueDescAr?: T;
  pillarPartnership?: T;
  pillarPartnershipAr?: T;
  pillarPartnershipDesc?: T;
  pillarPartnershipDescAr?: T;
  teamEyebrow?: T;
  teamEyebrowAr?: T;
  teamTitle?: T;
  teamTitleAr?: T;
  teamBtn?: T;
  teamBtnAr?: T;
  newsViewAll?: T;
  newsViewAllAr?: T;
  footerAbout?: T;
  footerAboutAr?: T;
  footerExplore?: T;
  footerExploreAr?: T;
  footerParticipants?: T;
  footerParticipantsAr?: T;
  footerContact?: T;
  footerContactAr?: T;
  footerUniversity?: T;
  footerUniversityAr?: T;
  footerPobox?: T;
  footerPoboxAr?: T;
  footerZip?: T;
  footerZipAr?: T;
  footerPhone?: T;
  footerPhoneAr?: T;
  footerFax?: T;
  footerFaxAr?: T;
  footerEmail?: T;
  footerEmailAr?: T;
  footerSubscribe?: T;
  footerSubscribeAr?: T;
  footerSubscribePlaceholder?: T;
  footerSubscribePlaceholderAr?: T;
  footerSubscribeBtn?: T;
  footerSubscribeBtnAr?: T;
  footerDisclaimer?: T;
  footerDisclaimerAr?: T;
  footerPrivacy?: T;
  footerPrivacyAr?: T;
  footerSitemap?: T;
  footerSitemapAr?: T;
  footerCopyright?: T;
  footerCopyrightAr?: T;
  footerResources?: T;
  footerResourcesAr?: T;
  footerStudying?: T;
  footerStudyingAr?: T;
  footerLibrary?: T;
  footerLibraryAr?: T;
  footerDatabases?: T;
  footerDatabasesAr?: T;
  newsPrev?: T;
  newsPrevAr?: T;
  newsNext?: T;
  newsNextAr?: T;
  newsReadMore?: T;
  newsReadMoreAr?: T;
  newsCollapse?: T;
  newsCollapseAr?: T;
  projectsArea?: T;
  projectsAreaAr?: T;
  navMedia?: T;
  navMediaAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}