/* THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD. */
/* DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */
import config from '@payload-config'
import '@payloadcms/next/css'
import {
  REST_DELETE,
  REST_GET,
  REST_OPTIONS,
  REST_PATCH,
  REST_POST,
  REST_PUT,
} from '@payloadcms/next/routes'

// --- Manual addition (not part of Payload's generated output) ---
// Explicitly sets this route's Vercel function duration to the Hobby-tier
// ceiling (300s, per vercel.com/docs/functions/configuring-functions/duration
// — with Fluid Compute, which is on by default, Hobby's default *and* max
// are both 300s already, so this mostly documents the ceiling rather than
// raising it). Uploads to the Media collection route through this same
// catch-all handler, and the generatePdfThumbnail afterChange hook
// (src/lib/pdfThumbnail.ts) defers its rasterization + second GitHub upload
// via next/server's after() — that deferred work still shares this same
// maxDuration ceiling per Vercel's docs, so this is worth keeping explicit
// even though it isn't a change from the current effective default. If this
// file is ever regenerated by Payload, re-add this line.
export const maxDuration = 300
// --- End manual addition ---

export const GET = REST_GET(config)
export const POST = REST_POST(config)
export const DELETE = REST_DELETE(config)
export const PATCH = REST_PATCH(config)
export const PUT = REST_PUT(config)
export const OPTIONS = REST_OPTIONS(config)
