/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as InformationRouteImport } from './routes/information'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AboutParticipantsRouteImport } from './routes/about.participants'
import { Route as AboutPartnersRouteImport } from './routes/about.partners'
import { Route as ActivitiesConferencesRouteImport } from './routes/activities.conferences'
import { Route as ActivitiesMeetingsRouteImport } from './routes/activities.meetings'
import { Route as ActivitiesSeminarsRouteImport } from './routes/activities.seminars'
import { Route as ActivitiesWindsorBirzeitRouteImport } from './routes/activities.windsor-birzeit'
import { Route as InformationDatabasesRouteImport } from './routes/information.databases'
import { Route as InformationReadingsRouteImport } from './routes/information.readings'
import { Route as MediaAnnouncementsRouteImport } from './routes/media.announcements'
import { Route as MediaClippingsRouteImport } from './routes/media.clippings'
import { Route as MediaNewsRouteImport } from './routes/media.news'
import { Route as MediaPhotosRouteImport } from './routes/media.photos'
import { Route as PublicationsAudiovisualRouteImport } from './routes/publications.audiovisual'
import { Route as PublicationsBooksRouteImport } from './routes/publications.books'
import { Route as PublicationsBrochuresRouteImport } from './routes/publications.brochures'
import { Route as PublicationsPapersRouteImport } from './routes/publications.papers'
import { Route as PublicationsPostersRouteImport } from './routes/publications.posters'
import { Route as PublicationsReportsRouteImport } from './routes/publications.reports'
import { Route as PublicationsThesesRouteImport } from './routes/publications.theses'
import { Route as ProjectsResearchIndexRouteImport } from './routes/projects.research.index'
import { Route as ProjectsResearchSlugRouteImport } from './routes/projects.research.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutParticipantsRoute = AboutParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AboutRoute,
} as any)
const AboutPartnersRoute = AboutPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AboutRoute,
} as any)
const ActivitiesConferencesRoute = ActivitiesConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => ActivitiesRoute,
} as any)
const ActivitiesMeetingsRoute = ActivitiesMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => ActivitiesRoute,
} as any)
const ActivitiesSeminarsRoute = ActivitiesSeminarsRouteImport.update({
  id: '/seminars',
  path: '/seminars',
  getParentRoute: () => ActivitiesRoute,
} as any)
const ActivitiesWindsorBirzeitRoute =
  ActivitiesWindsorBirzeitRouteImport.update({
    id: '/windsor-birzeit',
    path: '/windsor-birzeit',
    getParentRoute: () => ActivitiesRoute,
  } as any)
const InformationDatabasesRoute = InformationDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => InformationRoute,
} as any)
const InformationReadingsRoute = InformationReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => InformationRoute,
} as any)
const MediaAnnouncementsRoute = MediaAnnouncementsRouteImport.update({
  id: '/media/announcements',
  path: '/media/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaClippingsRoute = MediaClippingsRouteImport.update({
  id: '/media/clippings',
  path: '/media/clippings',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaNewsRoute = MediaNewsRouteImport.update({
  id: '/media/news',
  path: '/media/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaPhotosRoute = MediaPhotosRouteImport.update({
  id: '/media/photos',
  path: '/media/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsAudiovisualRoute = PublicationsAudiovisualRouteImport.update({
  id: '/audiovisual',
  path: '/audiovisual',
  getParentRoute: () => PublicationsRoute,
} as any)
const PublicationsBooksRoute = PublicationsBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => PublicationsRoute,
} as any)
const PublicationsBrochuresRoute = PublicationsBrochuresRouteImport.update({
  id: '/brochures',
  path: '/brochures',
  getParentRoute: () => PublicationsRoute,
} as any)
const PublicationsPapersRoute = PublicationsPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => PublicationsRoute,
} as any)
const PublicationsPostersRoute = PublicationsPostersRouteImport.update({
  id: '/posters',
  path: '/posters',
  getParentRoute: () => PublicationsRoute,
} as any)
const PublicationsReportsRoute = PublicationsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PublicationsRoute,
} as any)
const PublicationsThesesRoute = PublicationsThesesRouteImport.update({
  id: '/theses',
  path: '/theses',
  getParentRoute: () => PublicationsRoute,
} as any)
const ProjectsResearchIndexRoute = ProjectsResearchIndexRouteImport.update({
  id: '/projects/research/',
  path: '/projects/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsResearchSlugRoute = ProjectsResearchSlugRouteImport.update({
  id: '/projects/research/$slug',
  path: '/projects/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/activities': typeof ActivitiesRouteWithChildren
  '/information': typeof InformationRouteWithChildren
  '/publications': typeof PublicationsRouteWithChildren
  '/search': typeof SearchRoute
  '/about/participants': typeof AboutParticipantsRoute
  '/about/partners': typeof AboutPartnersRoute
  '/activities/conferences': typeof ActivitiesConferencesRoute
  '/activities/meetings': typeof ActivitiesMeetingsRoute
  '/activities/seminars': typeof ActivitiesSeminarsRoute
  '/activities/windsor-birzeit': typeof ActivitiesWindsorBirzeitRoute
  '/information/databases': typeof InformationDatabasesRoute
  '/information/readings': typeof InformationReadingsRoute
  '/media/announcements': typeof MediaAnnouncementsRoute
  '/media/clippings': typeof MediaClippingsRoute
  '/media/news': typeof MediaNewsRoute
  '/media/photos': typeof MediaPhotosRoute
  '/publications/audiovisual': typeof PublicationsAudiovisualRoute
  '/publications/books': typeof PublicationsBooksRoute
  '/publications/brochures': typeof PublicationsBrochuresRoute
  '/publications/papers': typeof PublicationsPapersRoute
  '/publications/posters': typeof PublicationsPostersRoute
  '/publications/reports': typeof PublicationsReportsRoute
  '/publications/theses': typeof PublicationsThesesRoute
  '/projects/research/$slug': typeof ProjectsResearchSlugRoute
  '/projects/research/': typeof ProjectsResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/activities': typeof ActivitiesRouteWithChildren
  '/information': typeof InformationRouteWithChildren
  '/publications': typeof PublicationsRouteWithChildren
  '/search': typeof SearchRoute
  '/about/participants': typeof AboutParticipantsRoute
  '/about/partners': typeof AboutPartnersRoute
  '/activities/conferences': typeof ActivitiesConferencesRoute
  '/activities/meetings': typeof ActivitiesMeetingsRoute
  '/activities/seminars': typeof ActivitiesSeminarsRoute
  '/activities/windsor-birzeit': typeof ActivitiesWindsorBirzeitRoute
  '/information/databases': typeof InformationDatabasesRoute
  '/information/readings': typeof InformationReadingsRoute
  '/media/announcements': typeof MediaAnnouncementsRoute
  '/media/clippings': typeof MediaClippingsRoute
  '/media/news': typeof MediaNewsRoute
  '/media/photos': typeof MediaPhotosRoute
  '/publications/audiovisual': typeof PublicationsAudiovisualRoute
  '/publications/books': typeof PublicationsBooksRoute
  '/publications/brochures': typeof PublicationsBrochuresRoute
  '/publications/papers': typeof PublicationsPapersRoute
  '/publications/posters': typeof PublicationsPostersRoute
  '/publications/reports': typeof PublicationsReportsRoute
  '/publications/theses': typeof PublicationsThesesRoute
  '/projects/research/$slug': typeof ProjectsResearchSlugRoute
  '/projects/research': typeof ProjectsResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/activities': typeof ActivitiesRouteWithChildren
  '/information': typeof InformationRouteWithChildren
  '/publications': typeof PublicationsRouteWithChildren
  '/search': typeof SearchRoute
  '/about/participants': typeof AboutParticipantsRoute
  '/about/partners': typeof AboutPartnersRoute
  '/activities/conferences': typeof ActivitiesConferencesRoute
  '/activities/meetings': typeof ActivitiesMeetingsRoute
  '/activities/seminars': typeof ActivitiesSeminarsRoute
  '/activities/windsor-birzeit': typeof ActivitiesWindsorBirzeitRoute
  '/information/databases': typeof InformationDatabasesRoute
  '/information/readings': typeof InformationReadingsRoute
  '/media/announcements': typeof MediaAnnouncementsRoute
  '/media/clippings': typeof MediaClippingsRoute
  '/media/news': typeof MediaNewsRoute
  '/media/photos': typeof MediaPhotosRoute
  '/publications/audiovisual': typeof PublicationsAudiovisualRoute
  '/publications/books': typeof PublicationsBooksRoute
  '/publications/brochures': typeof PublicationsBrochuresRoute
  '/publications/papers': typeof PublicationsPapersRoute
  '/publications/posters': typeof PublicationsPostersRoute
  '/publications/reports': typeof PublicationsReportsRoute
  '/publications/theses': typeof PublicationsThesesRoute
  '/projects/research/$slug': typeof ProjectsResearchSlugRoute
  '/projects/research/': typeof ProjectsResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/information'
    | '/publications'
    | '/search'
    | '/about/participants'
    | '/about/partners'
    | '/activities/conferences'
    | '/activities/meetings'
    | '/activities/seminars'
    | '/activities/windsor-birzeit'
    | '/information/databases'
    | '/information/readings'
    | '/media/announcements'
    | '/media/clippings'
    | '/media/news'
    | '/media/photos'
    | '/publications/audiovisual'
    | '/publications/books'
    | '/publications/brochures'
    | '/publications/papers'
    | '/publications/posters'
    | '/publications/reports'
    | '/publications/theses'
    | '/projects/research/$slug'
    | '/projects/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/information'
    | '/publications'
    | '/search'
    | '/about/participants'
    | '/about/partners'
    | '/activities/conferences'
    | '/activities/meetings'
    | '/activities/seminars'
    | '/activities/windsor-birzeit'
    | '/information/databases'
    | '/information/readings'
    | '/media/announcements'
    | '/media/clippings'
    | '/media/news'
    | '/media/photos'
    | '/publications/audiovisual'
    | '/publications/books'
    | '/publications/brochures'
    | '/publications/papers'
    | '/publications/posters'
    | '/publications/reports'
    | '/publications/theses'
    | '/projects/research/$slug'
    | '/projects/research'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/information'
    | '/publications'
    | '/search'
    | '/about/participants'
    | '/about/partners'
    | '/activities/conferences'
    | '/activities/meetings'
    | '/activities/seminars'
    | '/activities/windsor-birzeit'
    | '/information/databases'
    | '/information/readings'
    | '/media/announcements'
    | '/media/clippings'
    | '/media/news'
    | '/media/photos'
    | '/publications/audiovisual'
    | '/publications/books'
    | '/publications/brochures'
    | '/publications/papers'
    | '/publications/posters'
    | '/publications/reports'
    | '/publications/theses'
    | '/projects/research/$slug'
    | '/projects/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ActivitiesRoute: typeof ActivitiesRouteWithChildren
  InformationRoute: typeof InformationRouteWithChildren
  PublicationsRoute: typeof PublicationsRouteWithChildren
  SearchRoute: typeof SearchRoute
  MediaAnnouncementsRoute: typeof MediaAnnouncementsRoute
  MediaClippingsRoute: typeof MediaClippingsRoute
  MediaNewsRoute: typeof MediaNewsRoute
  MediaPhotosRoute: typeof MediaPhotosRoute
  ProjectsResearchSlugRoute: typeof ProjectsResearchSlugRoute
  ProjectsResearchIndexRoute: typeof ProjectsResearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/participants': {
      id: '/about/participants'
      path: '/participants'
      fullPath: '/about/participants'
      preLoaderRoute: typeof AboutParticipantsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/partners': {
      id: '/about/partners'
      path: '/partners'
      fullPath: '/about/partners'
      preLoaderRoute: typeof AboutPartnersRouteImport
      parentRoute: typeof AboutRoute
    }
    '/activities/conferences': {
      id: '/activities/conferences'
      path: '/conferences'
      fullPath: '/activities/conferences'
      preLoaderRoute: typeof ActivitiesConferencesRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/activities/meetings': {
      id: '/activities/meetings'
      path: '/meetings'
      fullPath: '/activities/meetings'
      preLoaderRoute: typeof ActivitiesMeetingsRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/activities/seminars': {
      id: '/activities/seminars'
      path: '/seminars'
      fullPath: '/activities/seminars'
      preLoaderRoute: typeof ActivitiesSeminarsRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/activities/windsor-birzeit': {
      id: '/activities/windsor-birzeit'
      path: '/windsor-birzeit'
      fullPath: '/activities/windsor-birzeit'
      preLoaderRoute: typeof ActivitiesWindsorBirzeitRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/information/databases': {
      id: '/information/databases'
      path: '/databases'
      fullPath: '/information/databases'
      preLoaderRoute: typeof InformationDatabasesRouteImport
      parentRoute: typeof InformationRoute
    }
    '/information/readings': {
      id: '/information/readings'
      path: '/readings'
      fullPath: '/information/readings'
      preLoaderRoute: typeof InformationReadingsRouteImport
      parentRoute: typeof InformationRoute
    }
    '/media/announcements': {
      id: '/media/announcements'
      path: '/media/announcements'
      fullPath: '/media/announcements'
      preLoaderRoute: typeof MediaAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/clippings': {
      id: '/media/clippings'
      path: '/media/clippings'
      fullPath: '/media/clippings'
      preLoaderRoute: typeof MediaClippingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/news': {
      id: '/media/news'
      path: '/media/news'
      fullPath: '/media/news'
      preLoaderRoute: typeof MediaNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/photos': {
      id: '/media/photos'
      path: '/media/photos'
      fullPath: '/media/photos'
      preLoaderRoute: typeof MediaPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/audiovisual': {
      id: '/publications/audiovisual'
      path: '/audiovisual'
      fullPath: '/publications/audiovisual'
      preLoaderRoute: typeof PublicationsAudiovisualRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/books': {
      id: '/publications/books'
      path: '/books'
      fullPath: '/publications/books'
      preLoaderRoute: typeof PublicationsBooksRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/brochures': {
      id: '/publications/brochures'
      path: '/brochures'
      fullPath: '/publications/brochures'
      preLoaderRoute: typeof PublicationsBrochuresRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/papers': {
      id: '/publications/papers'
      path: '/papers'
      fullPath: '/publications/papers'
      preLoaderRoute: typeof PublicationsPapersRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/posters': {
      id: '/publications/posters'
      path: '/posters'
      fullPath: '/publications/posters'
      preLoaderRoute: typeof PublicationsPostersRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/reports': {
      id: '/publications/reports'
      path: '/reports'
      fullPath: '/publications/reports'
      preLoaderRoute: typeof PublicationsReportsRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/theses': {
      id: '/publications/theses'
      path: '/theses'
      fullPath: '/publications/theses'
      preLoaderRoute: typeof PublicationsThesesRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/projects/research/': {
      id: '/projects/research/'
      path: '/projects/research'
      fullPath: '/projects/research/'
      preLoaderRoute: typeof ProjectsResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/research/$slug': {
      id: '/projects/research/$slug'
      path: '/projects/research/$slug'
      fullPath: '/projects/research/$slug'
      preLoaderRoute: typeof ProjectsResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutParticipantsRoute: typeof AboutParticipantsRoute
  AboutPartnersRoute: typeof AboutPartnersRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutParticipantsRoute: AboutParticipantsRoute,
  AboutPartnersRoute: AboutPartnersRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ActivitiesRouteChildren {
  ActivitiesConferencesRoute: typeof ActivitiesConferencesRoute
  ActivitiesMeetingsRoute: typeof ActivitiesMeetingsRoute
  ActivitiesSeminarsRoute: typeof ActivitiesSeminarsRoute
  ActivitiesWindsorBirzeitRoute: typeof ActivitiesWindsorBirzeitRoute
}

const ActivitiesRouteChildren: ActivitiesRouteChildren = {
  ActivitiesConferencesRoute: ActivitiesConferencesRoute,
  ActivitiesMeetingsRoute: ActivitiesMeetingsRoute,
  ActivitiesSeminarsRoute: ActivitiesSeminarsRoute,
  ActivitiesWindsorBirzeitRoute: ActivitiesWindsorBirzeitRoute,
}

const ActivitiesRouteWithChildren = ActivitiesRoute._addFileChildren(
  ActivitiesRouteChildren,
)

interface InformationRouteChildren {
  InformationDatabasesRoute: typeof InformationDatabasesRoute
  InformationReadingsRoute: typeof InformationReadingsRoute
}

const InformationRouteChildren: InformationRouteChildren = {
  InformationDatabasesRoute: InformationDatabasesRoute,
  InformationReadingsRoute: InformationReadingsRoute,
}

const InformationRouteWithChildren = InformationRoute._addFileChildren(
  InformationRouteChildren,
)

interface PublicationsRouteChildren {
  PublicationsAudiovisualRoute: typeof PublicationsAudiovisualRoute
  PublicationsBooksRoute: typeof PublicationsBooksRoute
  PublicationsBrochuresRoute: typeof PublicationsBrochuresRoute
  PublicationsPapersRoute: typeof PublicationsPapersRoute
  PublicationsPostersRoute: typeof PublicationsPostersRoute
  PublicationsReportsRoute: typeof PublicationsReportsRoute
  PublicationsThesesRoute: typeof PublicationsThesesRoute
}

const PublicationsRouteChildren: PublicationsRouteChildren = {
  PublicationsAudiovisualRoute: PublicationsAudiovisualRoute,
  PublicationsBooksRoute: PublicationsBooksRoute,
  PublicationsBrochuresRoute: PublicationsBrochuresRoute,
  PublicationsPapersRoute: PublicationsPapersRoute,
  PublicationsPostersRoute: PublicationsPostersRoute,
  PublicationsReportsRoute: PublicationsReportsRoute,
  PublicationsThesesRoute: PublicationsThesesRoute,
}

const PublicationsRouteWithChildren = PublicationsRoute._addFileChildren(
  PublicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ActivitiesRoute: ActivitiesRouteWithChildren,
  InformationRoute: InformationRouteWithChildren,
  PublicationsRoute: PublicationsRouteWithChildren,
  SearchRoute: SearchRoute,
  MediaAnnouncementsRoute: MediaAnnouncementsRoute,
  MediaClippingsRoute: MediaClippingsRoute,
  MediaNewsRoute: MediaNewsRoute,
  MediaPhotosRoute: MediaPhotosRoute,
  ProjectsResearchSlugRoute: ProjectsResearchSlugRoute,
  ProjectsResearchIndexRoute: ProjectsResearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
