[build]
builder = "NIXPACKS"
installCommand = "npm install"
buildCommand = "npm run build"

[deploy]
  startCommand = "node server.js"
healthcheckPath = "/admin"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
